Add hcloud Ansible Tutorial
LKaemmerling/community-content pull request #1
Opened 2019-04-26 12:07 UTC by LKaemmerling

2019-04-30 15:11 UTC, raspla reviewed
Looks good to me so far. Maybe use always `Ansible`, sometimes you have written lowercased `ansible`.

2019-04-30 15:11 UTC, n-se commented on tutorials/howto-hcloud-ansible/01.en.md
> +author_img: "https://avatars1.githubusercontent.com/u/4281581?s=400&v=4"
```suggestion
author_img: "https://avatars1.githubusercontent.com/u/4281581"
```

2019-04-30 15:11 UTC, n-se commented on tutorials/howto-hcloud-ansible/01.en.md
> +          server: "{{ server.hcloud_server.name}}"
Missing space at the end of the line?

2019-05-04 19:31 UTC, frommMoritz requested changes

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +       * We assume that you know what a server, an image, a server type and a volume is.
```suggestion
       * knowing what a server, an image, a server type and a volume is.
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +  * Visit Hetzner Cloud Console at [https://console.hetzner.cloud](https://console.hetzner.cloud), select your project, and create a new API Token.
I'm a bit confused here, the first point is `Hetzner Cloud API Token` and here you give instructions on how to create one. Wouldn't that be a underpoint while the knoweledge thats required should have it's own top level point?

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +* `hcloud-python` installed
```suggestion
* `hcloud-python` installed (`pip install hcloud`)
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +   * Just run `pip install hcloud`
```suggestion
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +In Ansible, you can control your infrastructure by using yaml files, which describe the state of your infrastructure. These files are called "Roles". Every role can have tasks. A task is something li
```suggestion
In Ansible you can control your infrastructure with yaml files. They describe the state of your infrastructure. These files are called "Roles". Every role can have tasks. A task is something like "create a server", "run a command on the server" or something else. You can control ansible with the `ansible` command. 
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +In Ansible, you can control your infrastructure by using yaml files, which describe the state of your infrastructure. These files are called "Roles". Every role can have tasks. A task is something li
```suggestion
In Ansible, you can control your infrastructure by using yaml files. They describe the state of your infrastructure. These files are called "Roles". Every role can have multiple tasks. A task is something like "create a server", "run a command on the server" or something else. You can control Ansible with the `ansible` command. 
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +For usage of the module, you only need to create a task like the following:
```suggestion
To use the module a taske like the following is all you need:
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +So you have learned something about the basic usage of Ansible. Now we will show you, how you can create a new server with the hcloud-server module. First of all, you should save the following YAML a
```suggestion
You have learned something about the basic usage of Ansible. Now we will show you, how you can create a new server with the hcloud-server module. First of all, you should save the following YAML as `hcloud-server.yml`.
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +When you now run `ansible-playbook -v hcloud-server.yml` you should get a output similar to this:
```suggestion
When you now run `ansible-playbook -v hcloud-server.yml` you should get a output similar to this:
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +You have created a server and a volume which is attached to the server!
```suggestion
You have created a server and an attached volume! 
```

2019-05-04 19:31 UTC, frommMoritz commented on tutorials/howto-hcloud-ansible/01.en.md
> +You now have a basic overview of the Hetzner Cloud Ansible modules. We have covered how you can create and delete resources and how to do more complex scenarios like attaching a volume to a server. Y
```suggestion
You now have a basic overview of the Hetzner Cloud Ansible modules. We covered how you can create and delete resources and how to do more complex scenarios like attaching a volume to a server. You can find more help on the [official documentation](https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#hcloud). If you need further help, just open an issue on our [Github Repository](https://github.com/ansible/ansible).
```

2019-05-06 04:40 UTC, LKaemmerling commented on tutorials/howto-hcloud-ansible/01.en.md
> +For usage of the module, you only need to create a task like the following:
```suggestion
To use the module, a task like the following is needed:
```

2019-05-06 04:40 UTC, LKaemmerling commented on tutorials/howto-hcloud-ansible/01.en.md
> +When you now run `ansible-playbook -v hcloud-server.yml` you should get a output similar to this:
```suggestion
When you run `ansible-playbook -v hcloud-server.yml` you should get an output similar to this below:

2019-05-06 04:43 UTC, LKaemmerling commented on tutorials/howto-hcloud-ansible/01.en.md
> +  * Visit Hetzner Cloud Console at [https://console.hetzner.cloud](https://console.hetzner.cloud), select your project, and create a new API Token.
I have changed it a bit, thank you!

2019-05-16 04:48 UTC, closed without merging